### PR TITLE
[MRG] updated hierarchical json files

### PR DESCRIPTION
**Pull request by gtdang**
Updated the hierarchical json files. These files were converted using the jones_2009 model for connection parameters. This is change from the previous files which did not have a base connectivity model configured.

### CODE REVIEW

**Comment by gtdang** [comment]
@ntolley 
I've updated the files in this PR with the latest conversion script. The latest conversion adds the removal of placeholder nulled drives.

**Comment by ntolley** [comment]
@gtdang I think something is going wrong with the conversion script, `jones_2009base.json` is empty:
image

**Comment by gtdang** [comment]
> @gtdang I think something is going wrong with the conversion script, `jones_2009base.json` is empty: image

Oops thanks for catching that! Must have made a mistake when renaming the file with terminal commands.

**Comment by ntolley** [comment]
Apologies for the delay, wanted to make some time to actually browse a few files and make sure the drives/attributes match what I expect

All looks good to me, thanks @gtdang!!

**Pull request merged**
